export { default as UserMiniMenu } from './UI/UserMiniMenu/UserMiniMenu'
export { default as TopMenu } from './TopMenu/TopMenu'
export { default as Slider } from './Slider/Slider'
export { default as ProjMiniCard } from './ProjectCards/MainCard/MainCard'
export { default as UserInfo } from './ProfilePage/UserInfo/UserInfo'
export { default as ProjWrapper } from './ProfilePage/ProjWrapper/ProjWrapper'
export { default as ProjectHeader} from './ProjectPage/ProjectHeader/ProjectHeader'
export { default as ButtonUI } from './UI/Button/Button'
export { default as Deadlines} from './ProjectPage/ProjectDeadlines/Deadlines'
export { default as People } from './ProjectPage/ProjectPeople/People'